apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lockeyapi-homolog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://bitbucket.org/mauricarmo/kubernetes'
    path: lockeyapi
    targetRevision: homolog
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: homolog
  syncPolicy:
    syncOptions:
      - CreateNamespace=true